import {
  Award,
  BadgeCheck,
  Bell,
  BellRing,
  Building,
  Building2,
  CalendarCheck,
  Camera,
  ClipboardCheck,
  Cross,
  Factory,
  FileText,
  Fingerprint,
  Flame,
  GraduationCap,
  HardDrive,
  Headset,
  Heart,
  HeartPulse,
  LayoutDashboard,
  Landmark,
  Package,
  PackageCheck,
  Scale,
  School,
  SearchCheck,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Siren,
  Star,
  Ticket,
  Users,
  Warehouse,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  award: Award,
  "badge-check": BadgeCheck,
  bell: Bell,
  "bell-ring": BellRing,
  building: Building,
  "building-2": Building2,
  "calendar-check": CalendarCheck,
  cctv: Camera,
  "clipboard-check": ClipboardCheck,
  cross: Cross,
  factory: Factory,
  fingerprint: Fingerprint,
  flame: Flame,
  "graduation-cap": GraduationCap,
  "hard-drive": HardDrive,
  headset: Headset,
  heart: Heart,
  "heart-pulse": HeartPulse,
  "layout-dashboard": LayoutDashboard,
  landmark: Landmark,
  "file-text": FileText,
  package: Package,
  "package-check": PackageCheck,
  scale: Scale,
  school: School,
  "search-check": SearchCheck,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  siren: Siren,
  star: Star,
  ticket: Ticket,
  users: Users,
  warehouse: Warehouse,
  workflow: Workflow,
  wrench: Wrench,
};

export function Icon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Cmp = ICONS[name] ?? Shield;
  return <Cmp className={className} aria-hidden="true" />;
}
